### ISSUE TITLE
bug(datepicker): legacy datepicker module

### ISSUE THREAD

**Issue by iKrishnaSahu** [angular/components#25977]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

We are migrating our library from angular v14 to latest v15 rc.
We have styled all the angular components based on our requirement including datepicker component.
We currently do not have enough capacity to migrate all the component to mdc components. So we are planning to use legacy components for a while.
While migrating, I can see datepicker component does not have legacy version of the same.
Is this expected?

### Reproduction

NA

### Expected Behavior

There should be a legacy datepicker component.

### Actual Behavior

There is no legacy datepicker component.

### Environment

- Angular:  15.0.0-rc.4
- CDK/Material: 15.0.0-rc.3
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
The datepicker works both with the legacy and non-legacy versions of `mat-form-field`.

**Comment by iKrishnaSahu** [comment]
@crisbeto We have extended [MatDatepickerInput](https://github.com/angular/components/blob/main/src/material/datepicker/datepicker-input.ts#L58) and created a timepicker in my library. So when we do super inside constructor of custom directive, it expects us to pass [MatFormField](https://github.com/angular/components/blob/main/src/material/datepicker/datepicker-input.ts#L127).

So after migrating to 15rc, If we pass legacy MatFormField instead, it throws below error - 

```
Error: libs/**/time-picker.directive.ts:130:52 - error TS2345: Argument of type 'MatLegacyFormField' is not assignable to parameter of type 'MatFormField'.
  Type 'MatLegacyFormField' is missing the following properties from type 'MatFormField': _textField, _iconPrefixContainer, _textPrefixContainer, _floatingLabel, and 24 more.

130     super(_elementRef, _dateAdapter, _dateFormats, _formField);
                                                       ~~~~~~~~~~




× Failed to compile.
```

**Comment by iKrishnaSahu** [comment]
@crisbeto Also there are some styling related changes in datepicker component which forces us to revisit styles for datepicker component unlike for other components which are having legacy component. This is the 2nd reason why I asked for legacy datepicker component.

**Comment by crisbeto** [comment]
I've opened a PR to address the typing issue. Until it gets released you should be able to safely cast to `any` in the constructor.

As for the styling, I believe it should be identical, judging by https://github.com/angular/components/pull/25648
