### PR TITLE
fix(cdk/overlay): resolve regression when overlay is imported through…

### PR DESCRIPTION
**Pull request by wagnermaciel**
… shorthand path (#22043)

Fixes a regression caused by #21896 where importing the overlay styles through
`~@angular/cdk/overlay` would result in a compilation error.

### CODE REVIEW

**Review by crisbeto — APPROVED** [review]
LGTM
