### PR TITLE
fix(cdk/overlay): resolve regression when overlay is imported through shorthand path

### PR DESCRIPTION
**Pull request by crisbeto**
Fixes a regression caused by #21896 where importing the overlay styles through `~@angular/cdk/overlay` would result in a compilation error.

### CODE REVIEW

**Review by wagnermaciel — APPROVED** [review]
lgtm

**Review by jelbourn — APPROVED** [review]
LGTM

**Comment by wagnermaciel** [comment]
@crisbeto This had merge conflicts with `11.2.x`, so I changed it to `target: minor` and created https://github.com/angular/components/pull/22086 to get it into `11.2.x` since this seemed urgent.
