### ISSUE TITLE
Renderer is not the exported member

### ISSUE THREAD

**Issue by akashb5432** [angular/components#18592]
After updating angular from 8 to 9 i am getting the below errors. 

ERROR in node_modules/ng2-material-dropdown/src/modules/components/menu-item/ng2-menu-item.d.ts:1:10 - error TS2724: Module '"../../../../../@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?

1 import { Renderer, ElementRef, OnDestroy } from '@angular/core';
           ~~~~~~~~

  node_modules/@angular/core/core.d.ts:5692:31
    5692 export declare abstract class Renderer2 {
                                       ~~~~~~~~~
    'Renderer2' is declared here.
node_modules/ng2-material-dropdown/src/modules/components/menu/ng2-dropdown-menu.d.ts:1:22 - error TS2724: Module '"../../../../../@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?

1 import { ElementRef, Renderer, QueryList } from '@angular/core';
                       ~~~~~~~~

  node_modules/@angular/core/core.d.ts:5692:31
    5692 export declare abstract class Renderer2 {
                                       ~~~~~~~~~
    'Renderer2' is declared here.

- Angular: 9.0.3
- CDK/Material: 9.0.1
- Browser(s): Chrom
- Operating System (e.g. Windows, macOS, Ubuntu):  Ubuntu

**Comment by crisbeto** [comment]
The error is from the `ng2-material-dropdown` library which isn't in this repo.

**Comment by jlegido** [comment]
@crisbeto could you please elaborate?

I'm facing same issue, and I don't have ng2-material-dropdown installed.

Thanks.

**Comment by crisbeto** [comment]
Material doesn't use `Renderer` at all so the error is coming from someplace else.

**Comment by jlegido** [comment]
@crisbeto many thanks for your quick reply, I will investigate what is going on on my project.

Thanks.

**Comment by akashb5432** [comment]
> After updating angular from 8 to 9 i am getting the below errors.
> 
> ERROR in node_modules/ng2-material-dropdown/src/modules/components/menu-item/ng2-menu-item.d.ts:1:10 - error TS2724: Module '"../../../../../@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?
> 
> 1 import { Renderer, ElementRef, OnDestroy } from '@angular/core';
> ~~~~~~~~
> 
> node_modules/@angular/core/core.d.ts:5692:31
> 5692 export declare abstract class Renderer2 {
> ~~~~~~~~~
> 'Renderer2' is declared here.
> node_modules/ng2-material-dropdown/src/modules/components/menu/ng2-dropdown-menu.d.ts:1:22 - error TS2724: Module '"../../../../../@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?
> 
> 1 import { ElementRef, Renderer, QueryList } from '@angular/core';
> ~~~~~~~~
> 
> node_modules/@angular/core/core.d.ts:5692:31
> 5692 export declare abstract class Renderer2 {
> ~~~~~~~~~
> 'Renderer2' is declared here.
> 
> * Angular: 9.0.3
> * CDK/Material: 9.0.1
> * Browser(s): Chrom
> * Operating System (e.g. Windows, macOS, Ubuntu):  Ubuntu

Thanks
Working now

**Comment by jlegido** [comment]
@akashb5432 how did you fix it?
Can you also please share your "package.json" file?
Thanks

**Comment by akashb5432** [comment]
@jlegido 
In my application ng2-material-dropdown was used by another module that is ngx-chips.
After updating ngx-chips, issue gets resolved.

**Comment by akashb5432** [comment]
> @akashb5432 how did you fix it?
> Can you also please share your "package.json" file?
> Thanks



"dependencies": {
    "@angular/animations": "~9.0.2",
    "@angular/cdk": "^8.2.1",
    "@angular/common": "~9.0.2",
    "@angular/compiler": "~9.0.2",
    "@angular/core": "~9.0.2",
    "@angular/forms": "~9.0.2",
    "@angular/material": "^9.0.1",
    "@angular/platform-browser": "~9.0.2",
    "@angular/platform-browser-dynamic": "~9.0.2",
    "@angular/router": "~9.0.2",
    "@fortawesome/angular-fontawesome": "^0.5.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.25",
    "@fortawesome/free-brands-svg-icons": "^5.11.2",
    "@fortawesome/free-solid-svg-icons": "^5.11.2",
    "@ngx-share/button": "^7.1.4",
    "@ngx-share/buttons": "^7.1.4",
    "@ngx-share/core": "^7.1.4",
    "@sentry/browser": "^5.10.2",
    "@types/html2canvas": "0.0.35",
    "@types/jspdf": "^1.3.1",
    "angulartics2": "6.3.1",
    "bootstrap": "^4.3.1",
    "file-saver": "^2.0.2",
    "google-libphonenumber": "^3.0.9",
    "hammerjs": "^2.0.8",
    "html-to-image": "^0.1.1",
    "html2canvas": "^1.0.0-rc.5",
    "jquery": "^3.4.1",
    "jspdf": "^1.5.3",
    "jszip": "^3.2.2",
    "leader-line": "^1.0.5",
    "ng-intercom": "^8.0.0",
    "ng2-material-dropdown": "^0.11.0",
    "ng2-materialize": "^1.3.2",
    "ng2-panzoom": "^2.2.2",
    "ngx-chips": "^2.1.0",
    "ngx-file-drop": "^8.0.8",
    "ngx-filesaver": "^8.0.0",
    "ngx-international-phone-number": "^1.0.4",
    "ngx-perfect-scrollbar": "^8.0.0",
    "ngx-toastr": "^10.0.4",
    "rxjs": "~6.5.4",
    "stream": "0.0.2",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.900.3",
    "@angular/cli": "~9.0.3",
    "@angular/compiler-cli": "~9.0.2",
    "@angular/language-service": "~9.0.2",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.7.5"
  }
