### ISSUE TITLE
bug(stepper): `markAllAsTouched` does not exist

### ISSUE THREAD

**Issue by dzhavat** [angular/components#33809]
### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

22.0.6

### Description

After upgrading from 22.0.6 to 22.1.5 I started getting a compile error that says

> Property 'markAllAsTouched' does not exist on type 'StepControl'.
  Property 'markAllAsTouched' does not exist on type 'Field&lt;unknown&gt;'.

<img width="930" height="191" alt="Image" src="https://github.com/user-attachments/assets/5f646972-3135-4d72-a0a8-06f616a0a27b" />

I think I've tracked the issue to https://github.com/angular/components/pull/33562 where `stepControl` was marked as `AbstractControl | Field<unknown>` where before it was simply `AbstractControl`

### Reproduction

StackBlitz link: https://stackblitz.com/edit/ukoi2xft?file=src%2Fexample%2Fstepper-overview-example.ts&startScript=start
Steps to reproduce:
1. 
2.

### Expected Behavior

The code should compile without errors

### Actual Behavior

Compile errors

### Environment

- Angular: 22.1.5
- CDK/Material: 22.1.5
- Browser(s): 
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by crisbeto** [comment]
We had to do it this way to support signal forms, but if you're not using those, you can cast the `stepControl` to `AbstractControl`.

**Comment by dzhavat** [comment]
Ended up using a similar `isField` util function as the one in the linked PR. Thanks for the help.
