### ISSUE TITLE
help(mat-icon): svgIcon not working after upgrade from 8.x to 9.x or 10x

### ISSUE THREAD

**Issue by no-more** [angular/components#20274]
#### What are you trying to do?

I'm trying to upgrade my application from 8.x to latest versions
I have the same issue with 9.x and 10.x
I have been able to fix all other upgrade issues but this one.
Application compile with and without AOT, but in browser I have not svgIcon. I have this error message instead : 
`Error: Error retrieving icon myNameSpace:sync! req.url.toLowerCase is not a function`

the error comes from @angular/common/http: 
```
/**
 * `HttpInterceptor` which adds an XSRF token to eligible outgoing requests.
 */
@Injectable()
export class HttpXsrfInterceptor implements HttpInterceptor {
  constructor(
      private tokenService: HttpXsrfTokenExtractor,
      @Inject(XSRF_HEADER_NAME) private headerName: string) {}

  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    const lcUrl = req.url.toLowerCase();
```
Except migration bug fixes I haven't changed any thing and the same code works fine with V8.x

#### What troubleshooting steps have you tried?

Upgrade to v10 and also upgrade all deps

#### Reproduction

Sorry but I currently don't know how to reproduce this bug. All I know is that same code was working in V8 and isn't in V9 and V10
  
#### Environment

Angular CLI: 10.0.5
Node: 14.8.0
OS: win32 x64

Angular: 10.0.8
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1000.5
@angular-devkit/build-angular      0.1000.5
@angular-devkit/build-ng-packagr   0.1000.5
@angular-devkit/build-optimizer    0.1000.5
@angular-devkit/build-webpack      0.1000.5
@angular-devkit/core               10.0.5
@angular-devkit/schematics         10.0.5
@angular-devkit/schematics-cli     0.1000.5
@angular/cdk                       10.1.3
@angular/cli                       10.0.5
@angular/flex-layout               10.0.0-beta.32
@angular/http                      7.2.16
@angular/material                  10.1.3
@angular/material-moment-adapter   10.1.3
@angular/pwa                       0.1000.5
@ngtools/webpack                   10.0.5
@schematics/angular                10.0.5
@schematics/schematics             0.1000.5
@schematics/update                 0.1000.5
ng-packagr                         10.0.3
rxjs                               6.6.2
typescript                         3.9.7
webpack                            4.43.0

**Comment by no-more** [comment]
This is what I have if I put a breakpoint, url is a `Module` instead of `string` :
![image](https://user-images.githubusercontent.com/3856871/90013876-2bc9e900-dcb7-11ea-98e1-cef6fa7d473b.png)

**Comment by no-more** [comment]
Manage to make it work by changing this:
```
matIconRegistry.addSvgIconInNamespace(
	"NS",
	"home,
	sanitizer.bypassSecurityTrustResourceUrl(
		require("material-design-icons/action/svg/production/ic_home_24px.svg")
	)
);
```
to: 
```
matIconRegistry.addSvgIconInNamespace(
	"NS",
	"home,
	sanitizer.bypassSecurityTrustResourceUrl(
		require("material-design-icons/action/svg/production/ic_home_24px.svg").default
	)
);
```

I don't close the issue because I don't understand why it does not work as before.
If anybody has an explanation. Thanks.

**Comment by crisbeto** [comment]
This seems like more of a build issue than something on our end. Maybe it was the result of a Webpack upgrade between major versions?

**Comment by no-more** [comment]
Thanks @crisbeto, after more testing I think you're right, still this happened after `ng update` and this does not seems to affect angular directly so I think there's something to dig here. But if you think it's doesn't you can close the issue.
Maybe using `require` is not the best way to include the icons, but it's quite useful as it automatically copy the svg to the dist folder and rename it for production (hash). Otherwise I will have to copy the file another way (don't want to copy all of them) and will not be able to add hash to them.

**Comment by jelbourn** [comment]
Closing this since it seems unrelated to Angular Material.
