### ISSUE TITLE
After upgrade to 9.0.0-rc.1 Receiving Error  - Export of name 'cdkOverlayOrigin' not found

### ISSUE THREAD

**Issue by naveedahmed1** [angular/components#17708]
#### Reproduction

After upgrading to `9.0.0-rc.1` my app started throwing below error:

```
main-es2015.92b15c9cc3a66d032b6c.js:1 ERROR Error: Export of name 'cdkOverlayOrigin' not found!
    at main-es2015.92b15c9cc3a66d032b6c.js:1
    at ra (main-es2015.92b15c9cc3a66d032b6c.js:1)
    at Module.zu (main-es2015.92b15c9cc3a66d032b6c.js:1)
    at template (main-es2015.92b15c9cc3a66d032b6c.js:1)
    at Ko (main-es2015.92b15c9cc3a66d032b6c.js:1)
    at Wo (main-es2015.92b15c9cc3a66d032b6c.js:1)
    at ba (main-es2015.92b15c9cc3a66d032b6c.js:1)
    at main-es2015.92b15c9cc3a66d032b6c.js:1
    at Wo (main-es2015.92b15c9cc3a66d032b6c.js:1)
    at oc.createEmbeddedView (main-es2015.92b15c9cc3a66d032b6c.js:1)
```
 
 
#### Expected Behavior

It should work without any error.

#### Environment

- Angular:9.0.0-rc.2
- CDK/Material:9.0.0-rc.1
- Browser(s):Chrome 
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by funnyfrish** [comment]
Im also getting following error:
Error: Assertion error: failed to find directive with exportAs: matMenu. 

Angular Material with Ivy gives always same error when using in template...

`Angular CLI: 9.0.0-next.10
Node: 10.15.3
OS: win32 x64
Angular: 9.0.0-next.15
... animations, bazel, common, compiler, compiler-cli, core
... forms, platform-browser, platform-browser-dynamic, router

Package                       Version
-------------------------------------------------------
@angular-devkit/architect     0.900.0-next.10
@angular-devkit/core          9.0.0-next.10
@angular-devkit/schematics    9.0.0-next.10
@angular/cdk                  8.2.3
@angular/cli                  9.0.0-next.10
@angular/material             8.2.3
@bazel/bazel                  1.1.0
@bazel/bazel-win32_x64        1.1.0
@bazel/benchmark-runner       0.1.0
@bazel/buildifier             0.29.0
@bazel/buildifier-win32_x64   0.29.0
@bazel/hide-bazel-files       0.39.1
@bazel/ibazel                 v0.10.3
@bazel/karma                  0.39.1
@bazel/protractor             0.39.1
@bazel/rollup                 0.39.1
@bazel/terser                 0.39.1
@bazel/typescript             0.39.1
@schematics/angular           9.0.0-next.10
@schematics/update            0.900.0-next.10
rxjs                          6.5.3
typescript                    3.6.4
 `

**Comment by devversion** [comment]
At first glance this looks like ngcc didn't run properly for `@angular/cdk`. @naveedahmed1 can you please provide a reproduction or check if `node_modules/@angular/cdk/overlay/overlay-directives.d.ts` has a class `CdkOverlayOrigin`. If so, please share that declaration.

**Comment by naveedahmed1** [comment]
I upgraded rxjs from `6.4.0` to `6.5.3` and it fixed the error.

**Comment by crisbeto** [comment]
Looks like it was a setup issue. Closing.
