### ISSUE TITLE
bug(cdk/schematics): Cannot find module '@angular-devkit/core/src/workspace/json/reader'

### ISSUE THREAD

**Issue by michaelfaith** [angular/components#27344]
### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16.0.3

### Description

It appears that the release of 16.1 has resurrected the behavior @Splaktar reported in [#21045](https://github.com/angular/components/issues/21045).  The other bug was locked, so I wasn't able to reply there.  It seemed the suggestion from @alan-agius4 was to install `@angular-devkit/core` in order to ensure you have the right version, but we're already doing that, and it's still presenting.  This all worked well in 16.0.3.  Looking at my `yarn.lock` there's only the one version of `@angular-devkit/core` installed.  Additionally, using any of the functions from `@angular/cdk/schematics` fail with a similar error.

Edit: based on @alan-agius4's comments below, it seems this is caused by `@angular/cdk` using deep imports in the schematics code, which is no longer allowed.  This tracks with my findings, as cdk 16.1.1 will work if I rollback the cli libraries to 16.0.3.

### Reproduction

`ng generate @angular/material:mdc-migration`

### Expected Behavior

Migration completes successfully

### Actual Behavior

When running the migration from the cli
```bash
Error: Cannot find module '@angular-devkit/core/src/workspace/json/reader' from '../../node_modules/@angular/cdk/schematics/utils/project-tsconfig-paths.js'

Require stack:
  D:/src/fabric/node_modules/@angular/cdk/schematics/utils/project-tsconfig-paths.js
  D:/src/fabric/node_modules/@angular/cdk/schematics/utils/index.js
  D:/src/fabric/node_modules/@angular/cdk/schematics/index.js
  D:/src/fabric/node_modules/@angular/material/schematics/ng-generate/mdc-migration/index_bundled.js
```

When using any functions from `@angular/cdk/schematics`
```bash
 Cannot find module '@angular-devkit/core/src/workspace/json/reader' from '../../node_modules/@angular/cdk/schematics/utils/project-tsconfig-paths.js'

    Require stack:
      D:/src/fabric/node_modules/@angular/cdk/schematics/utils/project-tsconfig-paths.js
      D:/src/fabric/node_modules/@angular/cdk/schematics/utils/index.js
      D:/src/fabric/node_modules/@angular/cdk/schematics/index.js
      schematics/ng-add/index.spec.ts
```

### Environment

- Angular: 16.0.3
- CDK/Material: 16.1.1
- Angular CLI: 16.1.1

**Comment by michaelfaith** [comment]
As I understand, for the other thread, a contributing factor to this is that these libraries aren't exhaustively declaring their peer dependencies, so-as not to force users to install stuff they're potentially not using.  Would declaring them, but marking them as  `peerDependenciesMeta.optional`, help with that concern?

**Comment by alan-agius4** [comment]
This is a different problem and unrelated to https://github.com/angular/components/issues/21045.

The problem here is that the schematics are using deep imports which is no longer allowed.

**Comment by michaelfaith** [comment]
I see.  That makes a bit more sense, and might explain why it starts working again if I roll the cli packages back to 16.0.3.  Was that blocked starting in 16.1.0?

**Comment by michaelfaith** [comment]
Updated the original post to include your assessment
