### ISSUE TITLE
Mat Tab Group & Ivy: selectedIndex not a property of HTMLElement

### ISSUE THREAD

**Issue by james-schwartzkopf** [angular/components#17079]
#### Reproduction

https://github.com/james-schwartzkopf/ng8-issues/tree/mat-tab-group-ivy-selected-index

Steps to reproduce:
1. yarn 
2. yarn run build
 
#### Expected Behavior

Should compile cleanly and tabs should work.

#### Actual Behavior

Error:
```
ERROR in src/app/app.component.html(2,16): Property 'selectedIndex' does not exist on type 'HTMLElement'.
```

#### Notes
May be related to #16750

The error doesn't occur using @angular/material 8.1.4 or with Ivy disabled.

I'm guessing this is due to the change to _MatTabGroupBase, maybe it needs an @Directive?  Not 100% sure how
inheritance works in Ivy.
https://github.com/angular/angular/pull/31379

#### Environment

- Angular: 8.2.6
- CDK/Material: 8.2.0

**Comment by enstenr** [comment]
I am facing same issue after enabling IVY. 

<mat-tab-group  class="col-lg-12" [selectedIndex]="activeAppraiserTabIndex">

The above worked perfectly before enabling IVY 

After enabling I get this error

 Property 'selectedIndex' does not exist on type 'HTMLElement'.

Not sure if its related with IVY

**Comment by ottodranik** [comment]
I confirm that. I am facing same issue with ivy too.

Because of that I can't do any url on tab -> I can't use index of tab in url and use "selectedIndex" for dynamically change tabs :(

**Comment by GenuineRex** [comment]
Same issue in Angular 9.

**Comment by gdjennings** [comment]
This also happens with
`<nav mat-tab-nav-bar>
   <a mat-tab-link [active]="...">
`
It's actually the only error I get now enabling Ivy in 8.2. Can workaround the error by disabling typecheck in tsconfig.app.json 
```
"angularCompilerOptions": {
    "enableIvy": true,
    "fullTemplateTypeCheck": false,
    "ivyTemplateTypeCheck": false,
    "allowEmptyCodegenFiles": true
  },
```

**Comment by obautista** [comment]
Any news on this issue?

**Comment by matteoulissi** [comment]
Apparently now it works though my code editor says: 
"Property selectedIndex is not provided by any applicable directives nor by mat-tab-group element"

**Comment by TheParad0X** [comment]
Same here for any input or output of mat-tab-group:
selectedTabChange
selectedIndex

**Comment by robo3945** [comment]
I'm not sure if my error is the same but after I migrated my app from Angular 8.2.3 to 9, only in the Editor (IntelliJIdea), I got:

<mat-tab-group [(selectedIndex)]="..."

==> "**Can't bind to [(selectedIndex)] since it is not provided by any applicable directives" on the "selectedIndex**"

                              (selectedTabChange)="...">
==> "**Event selectedTabChange is not emitted by any applicable directives nor by mat-tab-group element**"

But this happens only in WebStorm (the editor) because if i run the application with "ng serve" it works fine!

Any idea about it?

Sorry if i'm OT

**Comment by mmalerba** [comment]
I ran the original reproduction that was given and created an Ivy stackblitz with the given code, in both cases it compiled fine, so I think this was fixed.

**Comment by mariusvn** [comment]
Error still happening here on webstorm ...

**Comment by TheParad0X** [comment]
Same here.

**Comment by mmalerba** [comment]
I wonder if something in the webstorm toolchain is on an old version that has the issue. I don't think there's anything the Angular Components team can do since its already compiling fine at HEAD

**Comment by robo3945** [comment]
I personally did the test with the Webstorm 2020.1.2 RC and it solves my problem.

**Comment by TheParad0X** [comment]
Webstorm 2020.1.2 solves the problem for me too
