### ISSUE TITLE
[Angular 9] Compilation error after upgrading to v9

### ISSUE THREAD

**Issue by laneschmidt** [angular/components#18475]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/fork/components-issue

Steps to reproduce:
I can't reproduce this on stackblitz.
 
 
#### Expected Behavior

What behavior were you expecting to see?

The project to build after the upgrade was complete and I changed the import statements in the project from `import { Button } from '@angular/material'` format to `import { Button } from '@angular/material/button'` (the official Angular update guide said `ng update` would handle this but that wasn't the case). I'm using Lerna and Yarn Workspaces, and Yarn as a project package manager.

#### Actual Behavior

An error, coming from `../../node_modules/mat-progress-buttons/esm2015/mat-progress-buttons.js` immediately after `Compiling mat-progress-buttons : es2015 as esm2015`. 
The error:

```
@project/app: ERROR in Failed to compile entry-point mat-progress-buttons (es2015 as esm2015) due to compilation errors:
@project/app: ../../node_modules/mat-progress-buttons/esm2015/mat-progress-buttons.js:181:26 - error NG1010: Value at position 1 in the NgModule.imports of MatProgressButtonsModule is not a reference: [object Object]
@project/app: 181                 imports: [
@project/app:                              ~
@project/app: 182                     CommonModule,
@project/app:     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
@project/app: ...
@iproject/app: 187                     MatIconModule
@project/app:     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
@project/app: 188                 ],
@project/app:     ~~~~~~~~~~~~~~~~~
```

#### Environment

```
Angular CLI: 9.0.1
Node: 12.15.0
OS: darwin x64

Angular: 9.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
```

- Angular: 9.0.0
- CDK/Material: 9.0.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS Mojave 10.14.5

**Comment by devversion** [comment]
Hi @laneschmidt,

it looks like the error you sent is about a third-party library called `mat-progress-buttons`. It seems like that library doesn't process nicely with ngcc. 

Closing this as I don't think that this is an issue with Angular Material. Happy to chat more about this if you think it's an actual issue on our side. Thanks!

**Comment by insomnia1337** [comment]
bump the same problem
